export const EMAIL_CHANGED  = 'email_changed'
export const PASSWORD_CHANGED = 'password_changed'
export const LOGIN_USER_SUCCESS = 'login_user_success'
export const LOGIN_USER_FAIL = 'login_user_fail'
export const LOGIN_USER = 'login_user'
export const REGISTER_USER_FAIL = 'register_user_fail'
export const ROLE_CHANGED = 'role_changed'
export const LOGOUT_USER = 'logout_user'
export const ERROR_SHOWED = 'error_showed'
export const MESSAGE= 'message'
export const NOTVERIFIED = 'notverified'

export const USER_FETCH_SUCCESS = 'user_fetch_success'
export const USER_FETCH = 'user_fetch'
export const USER_FILLING_FORM = 'user_filling_form'
export const USER_FILLING = 'user_filling'
export const SUBMIT_BLOOD = 'submit_blood'
export const SUBMIT_BLOOD_SUCCESS = 'submit_blood_success'

export const POSITION_CHANGED = 'position_changed'
